const { chromium } = require('playwright');
const { pathToFileURL } = require('url');
const path = require('path');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  const errors = [];
  for (const width of [320,360,375,390,414]) {
    const page = await browser.newPage({ viewport:{ width,height:812 }, deviceScaleFactor:1, isMobile:true });
    page.setDefaultTimeout(5000);
    console.log(`checking ${width}`);
    page.on('pageerror', error => errors.push(`${width}: ${error.message}`));
    await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
    if (await page.locator('#operationsEntry').count() !== 1) errors.push(`${width}: workbench operations entry missing`);
    await page.locator('[data-go="activities"]').click();
    if (await page.locator('.activity-card').count() !== 3) errors.push(`${width}: published activity cards missing`);
    if ((await page.locator('.activity-card').first().getAttribute('data-id')) !== '1') errors.push(`${width}: activities not sorted by latest update`);
    if ((await page.locator('body').innerText()).includes('当前景区')) errors.push(`${width}: current scenic label remains visible`);
    if ((await page.locator('.activity-list').innerText()).includes('访问')) errors.push(`${width}: removed visit metrics remain visible`);
    if (await page.locator('[data-poster]').count() !== 3 || await page.locator('[data-operations]').count() !== 0 || await page.locator('[data-more]').count() !== 0) errors.push(`${width}: activity card action whitelist failed`);
    if (await page.locator('.activity-cover-fallback').count() !== 2) errors.push(`${width}: missing-image fallback example missing`);
    const longName = await page.locator('[data-id="4"] .activity-title-row h2').innerText();
    if ([...longName].length !== 30) errors.push(`${width}: 30-character activity name example invalid`);
    if ((await page.locator('.poster-entry').first().evaluate(el => el.getBoundingClientRect().height)) < 44) errors.push(`${width}: poster tap target below 44px`);
    await page.locator('[data-edit="1"]').evaluate(el => el.click());
    if (!(await page.locator('[data-page="config"]').isVisible())) errors.push(`${width}: clicking activity card did not open config`);
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('#operationsEntry').evaluate(el => el.click());
    if (!(await page.locator('[data-page="operationActivities"]').isVisible())) errors.push(`${width}: operation activity selector did not open`);
    if (await page.locator('[data-operation-activity]').count() !== 4) errors.push(`${width}: operation activity cards missing`);
    await page.locator('[data-operation-activity="1"]').evaluate(el => el.click());
    if (!(await page.locator('[data-page="operations"]').isVisible())) errors.push(`${width}: operations home did not open`);
    if (await page.locator('.operation-grid button').count() !== 4) errors.push(`${width}: operations shortcuts missing`);
    await page.locator('[data-op-go="records"]').evaluate(el => el.click());
    if (!(await page.locator('[data-page="records"]').isVisible())) errors.push(`${width}: all bookings page did not open`);
    if (await page.locator('.booking-row').count() !== 3) errors.push(`${width}: active booking rows missing`);
    await page.locator('[data-record-view="detail"]').evaluate(el => el.click());
    if (await page.locator('.booking-card').count() !== 3) errors.push(`${width}: detail booking cards missing`);
    await page.locator('#recordFieldSetting').evaluate(el => el.click());
    if (!(await page.locator('#fieldLayer').evaluate(el => el.classList.contains('open')))) errors.push(`${width}: detail field setting did not open`);
    await page.locator('[data-close="field"]').last().evaluate(el => el.click());
    await page.locator('[data-booking="1"]').first().evaluate(el => el.click());
    if (!(await page.locator('[data-page="bookingDetail"]').isVisible())) errors.push(`${width}: admin booking detail did not open`);
    if (!(await page.locator('#adminVisitorInfo').innerText()).includes('身份证号')) errors.push(`${width}: visitor snapshot fields missing`);
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('[data-record-status="cancelled"]').evaluate(el => el.click());
    if (await page.locator('.booking-card').count() !== 1) errors.push(`${width}: cancelled booking filter failed`);
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('[data-op-go="sessions"]').evaluate(el => el.click());
    if (await page.locator('.session-progress').count() !== 5) errors.push(`${width}: session progress rows missing`);
    await page.locator('[data-roster="s4"]').evaluate(el => el.click());
    if (!(await page.locator('[data-page="roster"]').isVisible())) errors.push(`${width}: roster page did not open`);
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('[data-op-go="export"]').evaluate(el => el.click());
    if (!(await page.locator('[data-page="export"]').isVisible())) errors.push(`${width}: export page did not open`);
    await page.locator('#generateExport').evaluate(el => el.click());
    if (await page.locator('#exportHistory>div').count() < 2) errors.push(`${width}: export record was not generated`);
    await page.locator('#backButton').evaluate(el => el.click());
    await page.locator('#backButton').evaluate(el => el.click());
    if (await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)) errors.push(`${width}: horizontal overflow`);
    await page.locator('[data-panel-go="activities"]').evaluate(el => el.click());
    await page.locator('[data-expand="1"]').evaluate(el => el.click());
    if (!(await page.locator('[data-id="1"]').evaluate(node => node.classList.contains('expanded')))) errors.push(`${width}: details did not expand`);
    await page.locator('[data-activity-status="offline"]').evaluate(el => el.click());
    if (await page.locator('.activity-card').count() !== 1 || (await page.locator('.activity-card').first().getAttribute('data-id')) !== '3') errors.push(`${width}: offline tab filter failed`);
    await page.locator('#activitySearch').fill('VIP');
    if (await page.locator('.activity-card').count() !== 1) errors.push(`${width}: search failed`);
    await page.screenshot({ path:path.join(__dirname,`qa-admin-${width}.png`), fullPage:true });
    console.log(`checked ${width}`);
    await page.close();
  }
  await browser.close();
  console.log(JSON.stringify({ ok:errors.length===0, errors },null,2));
  process.exitCode = errors.length ? 1 : 0;
})();
