const { chromium } = require('playwright');
const { pathToFileURL } = require('url');
const path = require('path');

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
  const errors = [];
  for (const width of [320, 360, 375, 390, 414]) {
    const page = await browser.newPage({ viewport: { width, height: 812 }, deviceScaleFactor: 1 });
    page.on('console', msg => { if (msg.type() === 'error') errors.push(`${width}: ${msg.text()}`); });
    page.on('pageerror', err => errors.push(`${width}: ${err.message}`));
    await page.goto(pathToFileURL(path.join(__dirname, 'index.html')).href);
    await page.waitForTimeout(100);
    if (await page.locator('#dateStrip [data-date="2026-08-13"]').count()) errors.push(`${width}: expired date remains visible`);
    if ((await page.locator('#dateStrip [data-date]').first().getAttribute('data-date')) !== '2026-08-14') errors.push(`${width}: date list does not start from today`);
    if (!(await page.locator('#dateStrip [data-date="2026-08-14"]').evaluate(el => el.classList.contains('selected')))) errors.push(`${width}: today is not selected by default`);
    if (await page.locator('#sessionList .session-card').count() !== 7) errors.push(`${width}: today's complete session list is incorrect`);
    if ((await page.locator('#sessionList').innerText()).includes('未开放')) errors.push(`${width}: hidden sessions still show unopen status`);
    if ((await page.locator('#nextButton').textContent()) !== '立即预约') errors.push(`${width}: primary action label is incorrect`);
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
    if (overflow) errors.push(`${width}: horizontal overflow`);
    await page.screenshot({ path: path.join(__dirname, `qa-${width}.png`), fullPage: true });
    await page.close();
  }
  const desktop = await browser.newPage({ viewport: { width: 1100, height: 900 } });
  desktop.on('pageerror', err => errors.push(`desktop: ${err.message}`));
  await desktop.goto(pathToFileURL(path.join(__dirname, 'index.html')).href);
  const dateStatusSamples = await desktop.evaluate(() => {
    const read = key => {
      const node = document.querySelector(`#dateStrip [data-date="${key}"] .date-status`);
      return { text: node?.textContent, fontSize: node ? getComputedStyle(node).fontSize : null };
    };
    return {
      available: read('2026-08-14'),
      full: read('2026-08-19'),
      unlimited: read('2026-08-20')
    };
  });
  if (new Set(Object.values(dateStatusSamples).map(item => item.fontSize)).size !== 1) errors.push('horizontal date status font sizes are inconsistent');
  if (dateStatusSamples.unlimited.text !== '不限额') errors.push('horizontal unlimited date label is not compact');
  if (await desktop.locator('[data-session-style="detail"]').count()) errors.push('removed detail session style is still available');
  if (!(await desktop.locator('#sessionList').evaluate(el => el.classList.contains('style-grid-named')))) errors.push('default session style is not named compact grid');
  await desktop.locator('.device-switch [data-width="320"]').click();
  if ((await desktop.locator('#phone').getAttribute('data-device-width')) !== '320') errors.push('desktop 320 device mode did not activate responsive state');
  await desktop.locator('[data-session="regular-12:30"]').click();
  await desktop.locator('[data-project="r1"]').click();
  const projectOverflow320 = await desktop.locator('#projectList').evaluate(list => {
    const bounds = list.getBoundingClientRect();
    return [...list.querySelectorAll('.project-card')].some(card => {
      const rect = card.getBoundingClientRect();
      return rect.left < bounds.left - 0.5 || rect.right > bounds.right + 0.5 || card.scrollWidth > card.clientWidth;
    });
  });
  if (projectOverflow320) errors.push('desktop 320 device mode project card overflows');
  await desktop.locator('.device-switch [data-width="375"]').click();
  for (const theme of ['forest', 'ocean', 'sunset']) {
    await desktop.locator(`.theme-dot[data-theme="${theme}"]`).click();
    const activeTheme = await desktop.locator('body').getAttribute('data-theme');
    if (activeTheme !== theme) errors.push(`theme switch failed: ${theme}`);
  }
  const hasHorizontalOverflow = await desktop.locator('#dateStrip').evaluate(el => el.scrollWidth > el.clientWidth);
  if (!hasHorizontalOverflow) errors.push('date strip does not have horizontal scroll range');
  await desktop.locator('#dateStrip').scrollIntoViewIfNeeded();
  await desktop.locator('#dateStrip').evaluate(el => { el.scrollLeft = 0; });
  const stripBox = await desktop.locator('#dateStrip').boundingBox();
  await desktop.mouse.move(stripBox.x + stripBox.width - 20, stripBox.y + 35);
  await desktop.mouse.down();
  await desktop.mouse.move(stripBox.x + 50, stripBox.y + 35, { steps: 8 });
  await desktop.mouse.up();
  const draggedScroll = await desktop.locator('#dateStrip').evaluate(el => el.scrollLeft);
  if (draggedScroll < 50) errors.push('date strip mouse drag did not scroll');
  await desktop.locator('[data-date-style="month"]').click();
  if (await desktop.locator('#openCalendar').isVisible()) errors.push('calendar entry remains visible in month schedule style');
  if (!(await desktop.locator('.month-tabs').evaluate(el => el.scrollWidth > el.clientWidth))) errors.push('month tabs have no horizontal scroll range');
  await desktop.locator('[data-date-month="10"]').click();
  if (!(await desktop.locator('[data-date="2026-10-01"]').isVisible())) errors.push('October schedule cards not visible');
  await desktop.locator('[data-date-month="9"]').click();
  if (!(await desktop.locator('[data-date="2026-09-01"]').isVisible())) errors.push('September schedule cards not visible');
  await desktop.locator('[data-date-month="8"]').click();
  await desktop.locator('[data-date="2026-08-14"]').click();
  if (!(await desktop.locator('#dateStrip [data-date="2026-08-14"]').evaluate(el => el.classList.contains('selected')))) errors.push('month schedule date selection failed');
  await desktop.locator('[data-date-month="1"]').click();
  if (!(await desktop.locator('[data-date="2027-01-01"]').isVisible())) errors.push('January 2027 schedule cards not visible');
  await desktop.locator('[data-date-month="8"]').click();
  if (await desktop.locator('#sessionList .session-card').count() < 5) errors.push('session status examples are incomplete');
  if ((await desktop.locator('#sessionList').innerText()).includes('未开放')) errors.push('session list still contains unopen status');
  await desktop.locator('[data-session-style="grid-named"]').click();
  if (!(await desktop.locator('#sessionList').evaluate(el => el.classList.contains('style-grid-named')))) errors.push('named compact session style failed');
  if (await desktop.locator('#sessionList .session-name').count() < 1) errors.push('named compact style has no session name');
  await desktop.locator('[data-session-style="grid-time"]').click();
  if (await desktop.locator('#sessionList .session-name').count() !== 0) errors.push('time-only compact style still shows session name');
  await desktop.locator('[data-session-style="rail-time"]').click();
  if (await desktop.locator('#sessionList .session-name').count() !== 0) errors.push('time-only rail style still shows session name');
  if (!(await desktop.locator('#sessionList').evaluate(el => el.scrollWidth > el.clientWidth))) errors.push('time-only rail has no horizontal scroll range');
  await desktop.waitForTimeout(100);
  const currentRailState = await desktop.locator('#sessionList').evaluate(el => ({ scrollLeft: el.scrollLeft, firstId: el.querySelector('[data-session]')?.dataset.session }));
  if (currentRailState.scrollLeft <= 0) errors.push('today session rail did not position at the current time');
  const currentSessionVisible = await desktop.locator('#sessionList').evaluate(el => {
    const current = [...el.querySelectorAll('[data-session]')].find(card => !card.classList.contains('state-closed'));
    if (!current) return false;
    const rail = el.getBoundingClientRect();
    const card = current.getBoundingClientRect();
    return card.left >= rail.left + 6 && card.right <= rail.right - 6;
  });
  if (!currentSessionVisible) errors.push('auto-positioned current session card is clipped');
  await desktop.locator('#sessionList').evaluate(el => { el.scrollLeft = 0; });
  await desktop.waitForTimeout(350);
  if ((await desktop.locator('#sessionList').evaluate(el => el.scrollLeft)) > 0) errors.push('session rail cannot scroll back to historical sessions');
  await desktop.locator('[data-session-data="vip"]').click();
  if (await desktop.locator('#sessionList .session-card').count() !== 12) errors.push('VIP complete half-hour schedule count is incorrect');
  await desktop.locator('[data-session-data="regular"]').click();
  if (await desktop.locator('#sessionList .session-card').count() !== 7) errors.push('regular complete schedule count is incorrect');
  if (!(await desktop.locator('#sessionList .session-card').first().innerText()).includes('-')) errors.push('time range is not displayed');
  await desktop.locator('[data-time-display="start"]').click();
  if ((await desktop.locator('#sessionList .session-card').first().innerText()).includes('-')) errors.push('start-only time still displays end time');
  const textAlign = await desktop.locator('#sessionList .session-card').first().evaluate(el => getComputedStyle(el).textAlign);
  if (textAlign !== 'center') errors.push('session card text is not centered');
  await desktop.locator('[data-session="regular-12:30"]').click();
  await desktop.locator('[data-project-style="simple"]').click();
  if ((await desktop.locator('#projectList').innerText()).includes('未开放')) errors.push('project list still contains unopen status');
  if (await desktop.locator('[data-project="r4"]').count()) errors.push('hidden unopen project remains in visitor list');
  if (await desktop.locator('#projectList img, #projectList p').count() !== 0) errors.push('simple project style still shows image or description');
  if (await desktop.locator('#projectList .state-closed').count() !== 0) errors.push('project list contains closed state');
  await desktop.locator('[data-project-style="detail"]').click();
  await desktop.locator('[data-time-display="range"]').click();
  await desktop.locator('[data-inventory-example="unlimited"]').click();
  await desktop.locator('[data-session-style="rail-time"]').click();
  if (await desktop.locator('#sessionList .state-open').first().innerText().then(text => !text.includes('不限名额'))) errors.push('unlimited session label is missing');
  await desktop.locator('#sessionList .state-open').first().click();
  if (await desktop.locator('#projectList .state-open').first().innerText().then(text => !text.includes('不限名额'))) errors.push('unlimited project label is missing');
  await desktop.locator('[data-project-module="off"]').click();
  if (await desktop.locator('#projectSection').isVisible()) errors.push('project section is visible when project module is disabled');
  if (await desktop.locator('#nextButton').isDisabled()) errors.push('next button is disabled without project module');
  await desktop.locator('[data-project-module="on"]').click();
  await desktop.locator('[data-inventory-example="limited"]').click();
  await desktop.locator('#sessionSection').scrollIntoViewIfNeeded();
  await desktop.screenshot({ path: path.join(__dirname, 'qa-session-rail.png'), fullPage: true });
  await desktop.screenshot({ path: path.join(__dirname, 'qa-variants.png'), fullPage: true });
  await desktop.locator('[data-date-style="strip"]').click();
  await desktop.locator('[data-session-style="grid-named"]').click();
  await desktop.locator('#dateStrip [data-date="2026-08-15"]').click();
  await desktop.waitForTimeout(3200);
  if (await desktop.locator('#noticeConfirm').isDisabled()) errors.push('notice countdown did not finish');
  await desktop.locator('#noticeConfirm').click();
  await desktop.locator('[data-session="regular-12:30"]').click();
  await desktop.locator('[data-project="r1"]').click();
  if (await desktop.locator('#nextButton').isDisabled()) errors.push('next button remained disabled');
  await desktop.locator('#nextButton').click();
  if (!(await desktop.locator('[data-page="form"]').isVisible())) errors.push('form page not visible');
  if ((await desktop.locator('#formSummary').innerText()).includes('常规溪降') === false) errors.push('form summary category value is missing');
  const formSummaryText = await desktop.locator('#formSummary').innerText();
  if (!formSummaryText.includes('分类') || !formSummaryText.includes('项目')) errors.push('form summary does not use direct category and project labels');
  if (formSummaryText.includes('体验项目') || formSummaryText.includes('体验线路')) errors.push('form summary still contains redundant experience labels');
  if ((await desktop.locator('#peopleCount').textContent()) !== '1') errors.push('group participant count does not default to 1');
  if (await desktop.locator('#peopleStock').count()) errors.push('stale remaining participant message is still visible');
  await desktop.locator('#minusPeople').click();
  if ((await desktop.locator('#peopleCount').textContent()) !== '1') errors.push('group participant count can drop below 1');
  await desktop.locator('[data-participant-mode="single"]').click();
  if (!(await desktop.locator('#singlePersonCard').isVisible()) || await desktop.locator('#groupPeopleCard').isVisible()) errors.push('single participant mode display is incorrect');
  if (!(await desktop.locator('#singlePersonCard').innerText()).includes('固定按 1 人统计')) errors.push('single participant mode count explanation is missing');
  await desktop.locator('[data-participant-mode="group"]').click();
  if (!(await desktop.locator('#groupPeopleCard').isVisible()) || await desktop.locator('#singlePersonCard').isVisible()) errors.push('group participant mode display is incorrect');
  await desktop.locator('#nameInput').fill('苏珊');
  await desktop.locator('#phoneInput').fill('13800138000');
  await desktop.locator('#sizeInput').selectOption({ label: '成人 M' });
  await desktop.locator('#submitButton').click();
  await desktop.waitForTimeout(1000);
  const participantWraps = await desktop.locator('#successSummary .participant-row').evaluate(row => {
    const label = row.querySelector('span').getBoundingClientRect();
    const value = row.querySelector('strong').getBoundingClientRect();
    return Math.abs(label.top - value.top) > 2;
  });
  if (participantWraps) errors.push('success participant count wraps to a second line');
  await desktop.locator('[data-go="detail"]').click();
  if (!(await desktop.locator('#detailNumberCard').isVisible())) errors.push('reservation number card is missing from reservation detail');
  if ((await desktop.locator('#detailReservationNumber').textContent()) !== '023') errors.push('reservation detail number is incorrect');
  await desktop.screenshot({ path: path.join(__dirname, 'qa-flow-form.png'), fullPage: true });
  await browser.close();
  console.log(JSON.stringify({ ok: errors.length === 0, errors }, null, 2));
  process.exitCode = errors.length ? 1 : 0;
})();
