const { chromium } = require('playwright');
const path = require('path');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  await page.goto('file://'+path.resolve(__dirname,'index.html'));
  await page.screenshot({path:path.resolve(__dirname,'qa-pc-list.png'),fullPage:true});
  const rows=await page.locator('#activityRows tr').count();
  const createButtons=await page.getByText('新建',{exact:true}).count();
  await page.locator('[data-promo]').first().click();
  const promoOpen=await page.locator('#promotionModal.open').count();
  await page.locator('[data-promo-tab="qr"]').click();
  const qrVisible=await page.locator('[data-promo-panel="qr"]:not(.hidden)').count();
  await page.locator('#promotionModal [data-close]').click();
  await page.locator('[data-operator]').first().click();
  const operatorOpen=await page.locator('#operatorModal.open').count();
  const operatorRows=await page.locator('#operatorRows tr').count();
  const operatorActionHeaders=await page.locator('#operatorModal th',{hasText:'操作'}).count();
  const bindingRoleTabs=await page.locator('[data-binding-role]').count();
  await page.locator('[data-binding-role="运营人员"]').click();
  const operationRoleRows=await page.locator('#operatorRows tr').count();
  await page.locator('#addOperator').click();
  const bindOpen=await page.locator('#bindOperatorModal.open').count();
  const bindChoices=await page.locator('#bindRows input[type=checkbox]').count();
  const disabledChoices=await page.locator('#bindRows input:disabled').count();
  await page.screenshot({path:path.resolve(__dirname,'qa-pc-bind-operators.png'),fullPage:true});
  await page.locator('#bindOperatorModal .close').click();
  await page.locator('#operatorModal [data-close]').click();
  await page.locator('#scenicMenu').click();
  const scenicRoleVisible=await page.locator('#scenicRolePage:not(.hidden)').count();
  const roleRows=await page.locator('#roleRows tr').count();
  const systemRoleTabs=await page.locator('[data-system-role]').count();
  await page.locator('[data-system-role="运营人员"]').click();
  const operationPoolRows=await page.locator('#roleRows tr').count();
  await page.screenshot({path:path.resolve(__dirname,'qa-pc-scenic-role.png'),fullPage:true});
  await page.locator('#addRoleOperator').click();
  const inviteOpen=await page.locator('#inviteRoleModal.open').count();
  const inviteQr=await page.locator('#inviteRoleModal .invite-qr').count();
  await page.screenshot({path:path.resolve(__dirname,'qa-pc-role-invite.png'),fullPage:true});
  console.log(JSON.stringify({rows,createButtons,promoOpen,qrVisible,operatorOpen,operatorRows,operatorActionHeaders,bindingRoleTabs,operationRoleRows,bindOpen,bindChoices,disabledChoices,scenicRoleVisible,roleRows,systemRoleTabs,operationPoolRows,inviteOpen,inviteQr,title:await page.title()}));
  await browser.close();
})();
